### ISSUE TITLE
GitHub action on stable25 fails

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/profiler#137]
I think the problem is that the app can not be enabled anymore on stable25 when checking out master, even with `--force`.
I think it would be good when we allow specifying a branch that should be cloned in 
https://github.com/nextcloud/profiler/blob/master/action/index.js#L62

Master also would currently clone a branch `cli` but that does not exist, but we would need this in a configurable way, so that we can checkout `stable25` when server is `stable25`, etc.
I wouldn't like to hard code it, so that it is easier to test changes in this app by specifying a different branch of the profiler to be checked out.

**Comment by icewind1991** [comment]
Fixed with #138
